# Auto-label PRs based on changed files

'documentation':
  - changed-files:
    - any-glob-to-any-file: ['*.md', 'docs/**/*']

'dependencies':
  - changed-files:
    - any-glob-to-any-file: ['package.json', 'yarn.lock', 'package-lock.json']

'database':
  - changed-files:
    - any-glob-to-any-file: ['src/database/**/*', '**/migrations/**/*', 'drizzle.config.ts']

'ui':
  - changed-files:
    - any-glob-to-any-file: ['src/components/ui/**/*', 'src/app/globals.css']

'api':
  - changed-files:
    - any-glob-to-any-file: ['src/app/api/**/*', 'src/services/**/*']

'auth':
  - changed-files:
    - any-glob-to-any-file: ['src/lib/auth/**/*', 'src/app/(login)/**/*']

'configuration':
  - changed-files:
    - any-glob-to-any-file: 
      - '*.config.*'
      - '*.json'
      - 'wrangler.jsonc'
      - '.github/**/*'

